
TOKEN = 'TOKEN' #str
API_ID = 'API_ID' #int
API_HASH = 'API_HASH' #str
SUDO = [] #list
ADMIN_CHAT = 'ADMIN_GROUP_ID' #int 
CHANNEL = 'CHANNEl_ID' #int
GROUP = 'DISSCUSSION_GROUP_ID' #int
CHANNEL_USERNAME = 'CHANNEL_USERNAME' #str
LINK = 'https://t.me/'+CHANNEL_USERNAME+'/{}?thread={}'
MONGODB_URI = 'MONGODB_URI'
